### ISSUE TITLE
don't change class/color when toggled

### ISSUE THREAD

**Issue by derekyau** [gfazioli/react-switch-button#22]
awesome component!

i'm using the switch button in the sense of switching between two options rather than 'on/off', is there an easy way I can disable it from changing color to the 'off-state' and just keep it 'on' the whole time?

**Comment by gfazioli** [comment]
Hi @derekyau ,

yes, you can do that by adding this styles in your page:

```css
<style>
    .rsbc-switch-button.rsbc-switch-button-flat-round input[type="checkbox"] + label:after,
    .rsbc-switch-button.rsbc-switch-button-flat-round:hover input[type="checkbox"]:checked + label,
    .rsbc-switch-button.rsbc-switch-button-flat-round input[type="checkbox"] + label
    {
      background-color: #579fcb !important;
    }
</style>
```

the above styles will override the default scheme colour.
