### ISSUE TITLE
how to change button backgroundColor?

### ISSUE THREAD

**Issue by wenwen1995** [gfazioli/react-switch-button#40]
how to change this switch button backgroundColor?

**Comment by gfazioli** [comment]
@wenwen1995 to change the background color

![image](https://user-images.githubusercontent.com/432181/47162056-8f6d7000-d2f3-11e8-9378-fe3f0acac015.png)

just override the following css rule

```css
.rsbc-switch-button.rsbc-switch-button-flat-round input[type="checkbox"] + label:before {
  background-color: red;
}
```
